version: '2.2'
services:
  in4331-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: in4331-es
    environment:
      - cluster.name=in4331-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 5000:9200
    networks:
      - esnet

volumes:
  esdata1:
    driver: local

networks:
  esnet:
